---
title: "notes"
author: "pjf"
date: "2026-01-19"
---

### todo

1.  lire PV, donation, acceptation

2.  succession du père

3.  donation-partage

4.  usufruit réservé par donation

5.  demander devis ehpad et facture maison

### faits synthétiques

- donation-partage est invalidée par l'arrété de cassation du 2 juillet 2025 et entraine la requalification simple.

- époux Fischer-Durrenberger mariés sous **l'ancien régime légal de la commununauté de biens meubles et acquêts**
- moitié indivise ne peut pas être disposé sans accord du tiers
- L’arrêt rendu par la première chambre civile de la Cour de cassation le 2 juillet 2025 (n° 23-16.329) marque une étape importante dans l’interprétation du régime juridique des donations-partages. Jusqu’alors, une incertitude persistait : une donation-partage comportant à la fois des attributions privatives et des quotes-parts indivises pouvait-elle conserver sa nature juridique de donation-partage ? La Haute juridiction répond clairement par la négative : l’attribution de biens en indivision, même partielle, suffit à disqualifier l’acte dans son ensemble.
- mais la tendance récente (arrêts 2024) montre une vigilance accrue sur les travaux valorisant le bien et l’intention libérale
