# Introduction

**Guidelines** selon Lettre de Paul aux Ephésiens Chapitre 5

> Ne vous compromettez pas en participant aux entreprises infructueuses que favorisent les ténèbres. Prenez plutôt parti contre elles, dénoncez leur caractère futile et mauvais. 12 Vous voyez bien ce que je veux dire, car tout ce qui se trame dans le secret est si honteux qu’on n’ose même pas en parler. 13 Mais quand on met ces choses à nu, leur véritable nature paraît à la lumière, et ce qui se laisse éclairer par la lumière est capable de devenir à son tour lumineux (n’était-ce pas votre cas ?).14 Comme il est dit (dans un cantique) : _Ô toi dormeur, réveille-toi, d’entre les morts, relève-toi, Sur toi luira le vrai soleil, le Christ t’éclairera._

> 15 Veillez donc, avec un soin tout particulier, à votre manière de vivre. Agissez avec la conscience de votre responsabilité. Ne vivez pas au jour le jour, sans penser à plus loin, comme ceux qui ne connaissent pas le vrai sens de la vie. 16 Comportez-vous en gens avisés qui se rendent compte en quels temps critiques nous vivons, et savent tirer le meilleur parti de la période présente. Devenez maîtres de votre temps, profitez de toutes les occasions favorables, malgré les difficultés de l’heure. Oui, précisément parce que nous vivons en un temps où domine le mal.