---
title: "pptJan"
format: revealjs
editor: visual
---

## Notes

-   Obtenir un Partage sur la base des elements cites par l'assignation
-   

## l'assignation en partage judiciaire

-   echec patent de l'accord amiable
-   

## le contexte

Je soussigné, Pierre Jacques FISCHER, demeurant au 39 rue de la Figairasse, Bât I, 34070 MONTPELLIER, ai l’honneur de vous saisir par la présente afin de solliciter un partage judiciaire concernant la succession de feu FISCHER née DURRENBERGER Aline, décédée selon l’acte de décès𝑑 de FISCHER née DURRENBERGER Aline du 19 Nov 2021, Numéro 37 - Mairie de Mertzwiller

En effet, trois années après le décès et deux tentatives de règlement amiable, il n’a pas été possible de parvenir à un accord entre les parties concernées. Par conséquent, je me vois contraint de demander l’intervention du tribunal pour procéder au partage des biens
conformément aux dispositions légales en vigueur.

En effet, les trois soeurs ont refusé tout à la fois, de faire la réunion fictive des biens distribués après la donation-partage de 1986 et de me restituer, sur l’immeuble sis à Mulhouse, le quasi-usufruit né d’un partage judiciaire qui m’a été imposé en 2011. Et
alors que le notaire refuse de m’adresser un procès-verbal de carence, la situation est dans l’impasse.

## l'historique

-   la donation-partage de 1986 : quatre parts egales
-   deux risques : une part indivise, une maison en devenir

## l'exception

-   vente forcee

## l'appauvrissement

## l'hebergement gratuit
