---
title: "recap arguments"
author: "pjf"
date: "2026-01-19"
---

### Recap_Mise_au_point

-   le **problème partagé** aujourd'hui par l'ensemble des héritiers est le fruit de la culture des irrégularités et des libéralités inégalitaires de Aline Durrenberger. La solution doit être une élaboration solidaire et non pas la focalisation sur la stigmatisation ou l'effort d'un seul héritier, car la causalité de tous les ennuis de succession se trouve dans la responsabilité des donateurs à l'origine et la conclusion de cette succession.

-   la **succession de Georges** n'a pas été ouverte, il faudra la régulariser en retracant le sort de la moitié de la succession de Georges, qui n'a pas été distribuée.

-   la **donation-partage est théoriqueent disqualifiée dans son ensemble** par la présence d’un seul bien attribué en indivision selon l’arrêt du 2 juillet 2025 (Cass. 1re civ., n° 23‑16.329). En effet, le risque réalisé de **l'adjudication judiciaire**, la **perte prématurée de l'usufruit** ainsi que la **taxation de la plus-value** annule les caractéristiques essentielles de la donation-partage, à savoir, premièrement le **caractère irrévocable** de la promesse de réunir in-fine la pleine propriété (causant ainsi la valeur de l'usufruit), en second lieu le **double avantage fiscal** de valeurs fixes et non taxables se transforme en pénalité payée, pour enlever enfin au réglement final de la succession toute la **pacification souhaitée**. La donation-partage se révéle ainsi caduque sans offrir de solutions mais la somme des préjudices est bien matérielle et elle s'impose par la contrainte principalement à Pierre sans que sa responsabilité soit engagée.

-   concernant la **perte de l'usufruit**, je demande qu'elle soit prise en compte comme un appauvrissement (puisqu'elle a enrichi définitement le donateur) et que le partage final soit corrigé pour rétablir l’équité. En invoquant l'Article 826 du Code civil : compensation des inégalités nées d’événements extérieurs et la Jurisprudence sur les « événements postérieurs affectant la substance du lot »

-   concernant les investissements en **travaux immobiliers** dont nous démontrons ( jurisprudence constante à l'appui) qu'ils sont à rapporter comme des libéralités à la succession car **fortement valorisant**, surtout tardifs pour ne plus pouvoir bénéficier à l'usufruitière, toujours **sans contre-partie**, ils se concentrent de surcroît pendant les dix dernières année sur trois et non plus quatre immeubles/bénficiaires. Celà constitue une **injustice structurelle** supplémentaire, qui augmente d'autant le préjudice de Pierre F.

-   quant à **l'hébergement gratuit permanent** dont bénéficie Michèle F. nous démontrons que cet avantage **disproportionné** par rapport au service apporté à la mère (dont l'ampleur du besoin reste à prouver) doit être considéré comme une libéralité intentionelle puisque la donation-partage lui ôtait explicitement tout usufruit avant le décès du dernier donateur. Dans ce cadre nous demandons la fourniture du devis de l'hypothétique EHPAD ainsi que le classement GIR associé. A ce propos nous avons étbalir que le train de vie moyen était de **4K€/mois**, ce qui permet de payer largement un EHPAD sans recours aux contributions des héritiers.

-   concernant l'immeuble en nature de terre **maison rue d'Eschach**, nous demandons à disposer des factures de la construction ainsi que l'élucidation du sort du fond de parcelle (à l'évidence exploitée par la société Pautler)

-   la comptabilisation du **mobilier restant** est classique et peut se faire au forfait.

### Recap_Arguments

-   il y a une objective **cascade d'irrégularités** doublée d'une implicite mais consciente **cascade d'inégalités** dont la somme des effets favorisent toujours les cohéritières et pénalisent Pierre F. Ces préjudices qui sont **l'héritage** de tous, doivent être compensés solidairement par le règlement final de ladite succession,ou à défaut d'accord par voie judiciaire.

-   la demande de réparation des préjudices subis par Pierre F est faite aux motifs qu'ils ne sont pas de sa responsabilité mais résultent à la fois d'événement extérieur, de gestion sciemment inégalitaire, de la caducité de la donation-partage vidée de son sens et de défaut de conseil.

-   l'immeuble de Mulhouse est vendu par adjudication judiciaire à la demande du tiers, ainsi la promesse de donation devient **caduque** et **inexécutable** pour disparition de l'immeuble et de l'usufruit futur. Le donateur a commis la faute de ne pas avoir protégé le bien promis (sachant que le bien était en indivision conflictuelle et qu'une vente judiciaire était plus que probable) et laissé croire que la donation serait réalisable. Cette faute pour défaut de conseil, peut aussi être retenue à l'encontre du notaire rédacteur de l'acte de donation, en première instance.

-   parmi les réactions possibles, on compte a) le **déni total** de la problématique solidairement partageable entre les héritiers et la causalité des actions de la défunte (mais cette prémière thèse est indéfendable), b) la demande de **requalification** à l'initiative de celles qui déploreraient être désavantagées par la valeur finale de leur lot (cette voie est suicidaire ne fut-ce que fiscalement); toutefois en renoncant raisonnablement à cette voie fiscalement suicidaire, on s'interdit de soulever par ailleurs tout argument de revalorisation, fictive ou réelle, c) le **refus de la succession?** pour éviter une perte (une explication pédagogique est ici sollicitée, sur la précédence et l'impact des décisions) d) un **accord amiable** selon la proposition de Me Schott (qui reflète un avis éclairé et pragmatique, intégrant le bien-fondé des arguments de tout bord et ressort favorable financièrement à toutes les parties). Cet accord a déjà été accepté par Pierre F. e) à défaut de toute contribution solidaire des cohéritières, poursuite du partage par **voie judiciaire** sur la base des arguments soutenus par le droit et la jurisprudence, et faisant la part des choses.

-   en tout état de cause l'ensemble des arguments est solidement étayé, ils sont donc peu ou prou **recevables**, il sont soutenus par une **jurisprudence constante** et ferme, ils seront probablement retenus peu ou prou par le juge. L'expertise si elle est demandée ne jouera que sur un ajustement des valeurs, qui ont été évaluées de manière très conservatrice.

-   concernant l'**appauvrissement**, en plus des libéralités consenties sans contrepartie et sans bénéfices, un calcul comptable montrent que le solde est **déficitaire de 26 K€** au bout des dix dernières années (si l'on exemptait l'apport de l'usufruit **74K€,** dont on peut dire qu'il a été pris à Pierre pour être donné aux soeurs ce qui creuse **un différentiel de traitement du double soit 148 K€.**

-   concernant **l'inégalité,** elle accorde à Michèle ce qui ne lui est même pas promis (savoir l'usage de 50% de son usufruit à convertir par exemple en investissement en or) alors que l'usufruit "réservé" in-fine à Pierre lui est de-facto repris avant le terme. deux poids, deux mesures sur un bien strictement de même nature: voilà l'injustice.

-   à la somme des arguments individuels concernant l'hébergement, la rue d'Eschbach, les travaux, l'usufruit et le mobilier, il faut ajouter l'argument résultant de leur mise en **faisceau** pour démontrer **l'inégalité systémique** quasiment sans exception qui à partir de la dépossession résultant de la vente judiciaire en 2011 ne fait qu'une seule chose: faire fondre le capital mobilier en le convertissant en valeurs ajoutées immobilières a profit des soeurs et sans vélleités de compenser le seul fils Pierre.
