---
title: "les demandes"
author: "pjf"
date: "2025-12-20"
categories: [finance]
---

Si la donation-partage de 1986 était voulue égalitaire en son temps, je soussigné Pierre F. demande la réévaluation de la situation au moment du décès par la double prise en considération a) du “quasi-usufruit” perdu et b) du rapport des libéralités dûment étayé. 

Pour ces raisons, je demande au tribunal

1. en première instance d’accorder la **restitution du quasi-usufruit** au profit de Pierre F. pour une valeur de 74.7 K€ au motif de lever le caractère discriminatoire dans le traitement des usufruits consommés avant le décès.

En effet il n’est pas recevable de faire valoir pour s’y opposer d’invoquer une
double iniquité: celle de refuser la restitution d’un usufruit perdu par Pierre F
et de défendre en même temps l’usufruit gagné par Michèle F.

2. d’effectuer ensuite, la réunion fictive de l’actif restant avec le **rapport des libéralités** chiffrées par le document lotz_technique et d’opérer le partage sur le modèle cidessous (ici sans la restitution préalalble de l’usufruit).
