---
title: "les parties"
author: "pjf"
date: "2025-12-20"
categories: [finance]
---

### les parties

la donation-partage du 19 Fev 1986 des époux Georges Fischer et Aline Durrenberger, par Me Lotz **en quatre parts égales de biens immobiliers** au profit des parties héritières et seuls quatre enfants, identifiés par le projet d’affirmation sacramentelle du 3 mars 2022 qui actualise les adresses comme suit:

- Michèle Fischer, demeurant à Mertzwiller (67580) 9 rue du Général Koenig

- Marguerite Besnier, demeurant à Goersdorf (67360) 9 rue des châtaigniers

- Aline Salzeman, demeurant à Armeau (89500) 34 rue de l’île de France

- Pierre Fischer, demeurant à Montpellier (34070) 39 rue de la Figairasse Bât I

### le patrimoine existant

en plus de la donation-partage sus-mentionnée la déclaration de succession du 3 mars 2022 projetée par Me Lotz, se limitait au **partage en quatre parts égales du seul actif net successoral** à hauteur de 129 026,58 €.

Cette proposition n’a pas trouvé l’accord de Pierre F. pour les raisons ci-dessous.
