---
title: "table des matières"
author: "pjf"
date: "2025-12-20"
description: "table des matières"
categories: [1_contexte]
---

### 1_CONTEXTE

- **les Faits**: donation originelle 1986/ adjudication Zanette 2011 => perte de l'usufruit; absence de réévaluation

- **les Diligences**: demande de rapport des libéralités / échec de l'accord amiable / assignation en partage judiciaire

### 2_ANALYSE

- **les Risques**: originels: terrain&maison, part indivise => manquement de Me Lotz, => requalification simple; à la succession: hébergement gratuit,  travaux tardifs, mobilier

- **la Méthodologie**: relevés bancaires => gros chèques => travaux => appauvrissement => absence de contrepartie => bénéficiaires des libéralités

- conclusions

### 3_ARGUMENTS 

- recevabilité des arguments selon part rapport des libéralités est dû ; ensemble


### 4_EVALUATIONS

- **Evaluation** selon les parties

- **Arguments** d'ensemble

- **les Conclusions** le rapport des libéralités est dû

### 5_DEMANDES

- **Demandes** : rapport des libéralités, tableau de répartition
 compensation de usufruit perdu
 
### 6_ALTERNATIVES

- les perspectives judiciaires

- à défault d'aménagement
