project:
  type: website
  output-dir: docs

execute:
  echo: false
  
website:
  title: "Partage26"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme:
      - lumen
    css: styles.css
  pdf:
    documentclass: scrartcl
    classoption: [landscape]
    papersize: A4
    geometry:
      - top=30mm
      - left=40mm
      - right=40mm
      - heightrounded
    mainfont: Lato
    monofont: Arial
    colorlinks: true
filters: []
