---
title: "les motifs"
author: "pjf"
date: "2025-12-20"
categories: [finance]
---

- la demande de **restitution** de 74700 € correspondant à **l’usufruit perdu** précocemment par la vente judiciaire forcée en 2012 du lot immobilier de Pierre F. (le nuproprétaire) se heurte à un refus des trois soeurs alors même qu’elles défendent Michèle F (nue-propriétaire) qui a consommé l’usufruit sur son lot avant le décès du de cujus. Considérant l’égalité dans la nature des biens (i.e. l’usufruit sur le bien immobiliier dans la période entre la donation et le décès ), ainsi que l’égalité ès qualité d’héritier, il n’est pas recevable de leur appliquer in fine une règle de partage
doublement discriminatoire et inique.

- la lettre lotz_rapport_signe.pdf du 21 Juin 2024 demande le rapport des
libéralités, sérieusement étayé par le chiffrage et l’argumentaire du document lotz_technique-v0.99.pdf qui analyse les factures afférentes aux gros chèques (préalablement identifiés sur les relevés bancaires), et permet d’identifier la nature, le montant et les bénéficiaires des gros travaux ainsi que le sort de l’usufruit. Cette étude conclut à un transfert massif et tardif de libéralités déguisées aux profit des seules soeurs concomittant à l’appauvrissement de la donatrice.

- en résumé, le **rapport des libéralités** (dont l’effet touchera l’ensemble des héritiers) demande à retenir ce qui est classique en pareil cas, à savoir les investissements en **gros travaux** (133 K€), le bénéfice du **logement gratuit** sur 35 ans (160 K€), la valeur du **mobilier restant** (30 K€) et la **maison** (160 K€) érigée après la donation de 1986 sur le terrain nu sis à Mertzwiller 9 rue d’Eschbach (lot de Marguerite B.) et de refaire en conséquence le partage de la réunion fictive ainsi obtenue. Cf détail sous “Demandes”.

- enfin, **l’argument du faisceau** réside dans l’observation que les avantages (dont la matérialité non négigeable se monte à 450 K€) sont toujours au bénéfice des soeurs et au détriment du fils.